[tool.poetry]
name = "trees"
version = "0.1.0"
description = ""
authors = ["Antonis Mand <antonis.mand@yahoo.com>"]
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.11"
econml = "^0.15.0"
pycit = "^0.0.7"
matplotlib = "^3.9.0"
networkx = "^3.3"
numpy = "<2.0.0"
causalml = "^0.15.1"
ipywidgets = "^8.1.3"
duecredit = "^0.10.2"
pandasql = "^0.7.3"
polars = "^1.2.1"
tqdm = "^4.66.4"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.4"
nbconvert = "^7.16.4"
notebook = "^7.2.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
